### ISSUE TITLE
Moving to a new location

### ISSUE THREAD

**Issue by Ooshkar** [trackmania-rl/tmrl#74]
Hey im having some trouble with moving my tmrl file because when i move it i get this 
`PS F:\TMRL-AI> python -m tmrl --server
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "C:\Users\liamr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\tmrl\__init__.py", line 31, in <module>
    from tmrl.config.config_objects import CONFIG_DICT
  File "C:\Users\liamr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\tmrl\config\config_objects.py", line 8, in <module>
    import tmrl.config.config_constants as cfg
  File "C:\Users\liamr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\tmrl\config\config_constants.py", line 16, in <module>
    with open(CONFIG_FILE) as f:
         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\liamr\\TmrlData\\config\\config.json'`
and i dont know how to change the location

thank you

**Comment by Ooshkar** [comment]
also how do i make a new algorithm? do i change the algorithm in the config or do i need to make a file somewhere?

**Comment by yannbouteiller** [comment]
Hi, at the moment it is not possible to move the `TmrlData` folder, it needs to stay in the home folder (this is where `tmrl` looks for `config.json`, that it cannot find in your error.

**Comment by yannbouteiller** [comment]
Making a new algorithm amounts to making a new `TrainingAgent`, if this is for TrackMania you can modify the [competition script](https://github.com/trackmania-rl/tmrl/blob/master/tmrl/tuto/competition/custom_actor_module.py). If this is for your own robot application, you can modify the [full tutorial script](https://github.com/trackmania-rl/tmrl/blob/master/tmrl/tuto/tuto.py) with the help of the tmrl python tutorial.

(Closing as this is not a library issue, please use the discussion sections for questions and feature requests)

**Comment by Ooshkar** [comment]
Thank you
