### ISSUE TITLE
Cannot import tmrl

### ISSUE THREAD

**Issue by SakshamV** [trackmania-rl/tmrl#84]
I get the following error when I try and import tmrl or run >python -m tmrl --test:

C:\Users\saksh>python -m tmrl --test
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "C:\Users\saksh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\tmrl\__init__.py", line 33, in <module>
    from tmrl.config.config_objects import CONFIG_DICT
  File "C:\Users\saksh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\tmrl\config\config_objects.py", line 9, in <module>
    import tmrl.config.config_constants as cfg
  File "C:\Users\saksh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\tmrl\config\config_constants.py", line 37, in <module>
    BUFFERS_MAXLEN = TMRL_CONFIG["BUFFERS_MAXLEN"]  # Maximum length of the local buffers for RolloutWorkers, Server and TrainerInterface
                     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'BUFFERS_MAXLEN'

**Comment by yannbouteiller** [comment]
Hi, did you remove the BUFFERS_MAXLEN entry from `config.json`?

A sane version of `config.json` is available in `TmrlData/resources` for backup if you changed that.

**Comment by SakshamV** [comment]
That worked, thanks!
