### ISSUE TITLE
error when running tmrl, I have followed the intructions and reinstalled pytorch to see if thats the issue and it still doesant work

### ISSUE THREAD

**Issue by jakefromstatesss** [trackmania-rl/tmrl#92]
C:\Users\jake>python -m tmrl
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\jake\AppData\Roaming\Python\Python39\site-packages\tmrl\__init__.py", line 35, in <module>
    from tmrl.config.config_objects import CONFIG_DICT
  File "C:\Users\jake\AppData\Roaming\Python\Python39\site-packages\tmrl\config\config_objects.py", line 10, in <module>
    from tmrl.training_offline import TorchTrainingOffline
  File "C:\Users\jake\AppData\Roaming\Python\Python39\site-packages\tmrl\training_offline.py", line 6, in <module>
    import torch
  File "C:\Users\jake\AppData\Roaming\Python\Python39\site-packages\torch\__init__.py", line 141, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\jake\AppData\Roaming\Python\Python39\site-packages\torch\lib\shm.dll" or one of its dependencies.

**Comment by jakefromstatesss** [comment]
Fixed by reinstalling python and all dependencies

**Comment by yannbouteiller** [comment]
Hi, there is a problem with your pytorch installation.

I recommend using Anaconda for installing pytorch and tmrl on Windows. Using a Microsoft packaging of python sounds like deliberately asking for trouble.

Closing as this is not a tmrl issue.
